Machine learning with pycaret module on python

resources:
https://pycaret.gitbook.io/docs/get-started/tutorials
https://colab.research.google.com/github/pycaret/pycaret/blob/master/tutorials/Tutorial%20-%20Regression.ipynb#scrollTo=87c1a007 
https://towardsdatascience.com/5-things-you-are-doing-wrong-in-pycaret-e01981575d2a

In [ ]:
#pip install pycaret

In [11]:
# Import dataset from pycaret repository
from pycaret.datasets import get_data
data = get_data('insurance')

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [12]:
# import pycaret regression and init setup
from pycaret.regression import *
s = setup(data, target = 'charges', session_id = 123)

In [15]:
# import RegressionExperiment and init the class
from pycaret.regression import RegressionExperiment
exp = RegressionExperiment()

# check the type of exp
type(exp)

pycaret.regression.oop.RegressionExperiment

In [16]:
# init setup on exp
exp.setup(data, target = 'charges', session_id = 123)

In [17]:
# compare baseline models
best = compare_models()

In [ ]:
#not using the best because of run time. May use gradient boosting when there is time.

In [ ]:
#best = create_model('gbr') #choose gradient boosting regressor (gbr) #to avoid plot errors with some models

In [ ]:
best = create_model('lr') #choose lr to run quickly and plot errors with some models

### Analyze Model

In [ ]:
# plot residuals
plot_model(best, plot = 'residuals')

In [ ]:
# plot error
plot_model(best, plot = 'error')

In [ ]:
# plot feature importance
plot_model(best, plot = 'feature')

## Prediction
The `predict_model` function returns `prediction_label` as new column to the input dataframe. When data is `None` (default), it uses the test set (created during the setup function) for scoring.